config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('post.urls', namespace='post')),
]

post/urls.py
from django.urls import path
from post.views import create_post, list_post

app_name = 'post'

urlpatterns = [
    path('', list_post, name='list'),
    path('create/', create_post, name='create'),
]

post/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    text = models.TextField(max_length=10000, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    is_hidden = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self) -> str:
        return self.text

    class Meta:
        ordering = ('created_at', )
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

post/forms.py
from django import forms
from post.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'image', 'is_hidden')

    def text_attr(self, field):
        field.widget.attrs.update({
            'class': 'form-control',
            "name": "user_activity",
            "placeholder": "Share what you've been up to..."
        })

    def image_attr(self, field):
        field.widget.attrs.update({
            'class': 'form-control'
        })

    def is_hidden_attr(self, field):
        field.widget.attrs.update({
            'class': 'form-check-input'
        })

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            method = getattr(self, f'{field_name}_attr', None)
            if method:
                method(field)

post/views.py
from django.shortcuts import render, redirect
from post.forms import PostForm
from django.urls import reverse
from post.models import Post

# Create your views here.


def create_post(request, *args, **kwargs):
    method = request.method.lower()
    if method == 'get':
        form = PostForm()
    elif method == 'post':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('post:list'))

    return render(
        request=request,
        template_name='post/create.html',
        context={'form': form}
    )


def list_post(request, *args, **kwargs):
    posts = Post.objects.all()
    form = PostForm()
    
    return render(
        request=request,
        template_name='post/create.html',
        context={
            'posts': posts,
            'form': form
        }
    )

post/templates/post/create.html
{% extends 'base.html' %} 

{% block content%}
<div class="col-lg-8">
  {% include 'component/profile.html' %}
  <div class="panel">
    <div class="panel-heading">
      <h3 class="panel-title">Activity Feed</h3>
    </div>
    <div class="panel-content panel-activity">

      {% include 'component/feed_form.html' %}
      
      {% include 'component/feed_list.html' %}
    </div>
  </div>
</div>
{% endblock %}

templates/component/feed_form.html
<form action="{% url 'post:create' %}" method="post" enctype="multipart/form-data" class="panel-activity__status">
  {% csrf_token %} 
  {{ form.text }}
  <div class="actions">
    <div class="btn-group">
      <button
        type="button"
        class="btn-link"
        title=""
        data-toggle="tooltip"
        data-original-title="Post an Image"
      >
        <i class="fa fa-image"></i>
      </button>
    </div>
    <button type="submit" class="btn btn-sm btn-rounded btn-info">Post</button>
  </div>
</form>

templates/component/feed_list.html
<ul class="panel-activity__list">
  {% for post in posts %}
  <li>
    <i class="activity__list__icon fa fa-question-circle-o"></i>
    <div class="activity__list__header">
      <img src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="" />
      <a href="#">John Doe</a> Posted the question:
      <a href="#">How can I change my annual reports for the better effect?</a>
    </div>
    <div class="activity__list__body entry-content">
      <p>
        {{ post.text }}
      </p>
    </div>
    <div class="activity__list__footer">
      <a href="#"> <i class="fa fa-thumbs-up"></i>123</a>
      <a href="#"> <i class="fa fa-comments"></i>23</a>
      <span> <i class="fa fa-clock"></i>{{ post.created_at }}</span>
    </div>
  </li>
  {% endfor %}
</ul>

templates/component/profile.html
<div class="panel profile-cover">
    <div class="profile-cover__img">
      <img src="https://bootdey.com/img/Content/avatar/avatar6.png" alt="" />
      <h3 class="h3">Henry Foster</h3>
    </div>
    <div class="profile-cover__action bg--img" data-overlay="0.3">
      <button class="btn btn-rounded btn-info">
        <i class="fa fa-plus"></i>
        <span>Follow</span>
      </button>
      <button class="btn btn-rounded btn-info">
        <i class="fa fa-comment"></i>
        <span>Message</span>
      </button>
    </div>
    <div class="profile-cover__info">
      <ul class="nav">
        <li><strong>26</strong>Projects</li>
        <li><strong>33</strong>Followers</li>
        <li><strong>136</strong>Following</li>
      </ul>
    </div>
  </div>